apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: sock-shop-mops
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - port: 80
      targetPort: 8079
      nodePort: 30001
