apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop-mops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: weaveworksdemos/front-end:0.3.12
          ports:
            - containerPort: 8080
